### ISSUE TITLE
Ignoruoti Twitter retweetus

### ISSUE THREAD

**Issue by Pawka** [ntacamp/social-hashtag#1]
Reiktų ignoruoti Twitterio retweetus, nes pasidaro daug vienodos žinutės kopijų.

Pakaktų tiesiog tikrinti ar source'as yra Twitter ir ar žinutė prasideda "RT ". Jei taip - ignoruoti.

**Comment by arnaspet** [comment]
done, norint excludinti retweetus reiktų perduot parametrą
`new TwitterDataFormatter(['includeRetweets' => false]))`
